# Branch Protection Rules Configuration
# This file defines the branch protection rules for main and develop branches
# Note: These rules need to be applied via GitHub API or manually in the repository settings

protection_rules:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        # Number of approvals required
        required_approving_review_count: 2
        # Dismiss stale PR approvals when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from CODEOWNERS
        require_code_owner_reviews: true
        # Prevent PR authors from approving their own PRs
        dismissal_restrictions:
          users: []
          teams: []
      
      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # Required status checks
        contexts:
          - "Security Audit"
          - "Lint and Type Check"
          - "Run Tests"
          - "Build Application"
      
      # Enforce all configured restrictions for administrators
      enforce_admins: true
      
      # Prevent direct pushes to the branch
      restrictions:
        users: []
        teams: []
        apps: []
      
      # Allow force pushes and deletions
      allow_force_pushes: false
      allow_deletions: false
      
      # Require signed commits
      required_signatures: false
      
      # Require linear history
      required_linear_history: true
      
      # Allow bypass for specific users/teams
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []
  
  - name: develop
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        # Number of approvals required
        required_approving_review_count: 1
        # Dismiss stale PR approvals when new commits are pushed
        dismiss_stale_reviews: true
        # Require review from CODEOWNERS
        require_code_owner_reviews: true
        # Prevent PR authors from approving their own PRs
        dismissal_restrictions:
          users: []
          teams: []
      
      # Require status checks to pass before merging
      required_status_checks:
        # Require branches to be up to date before merging
        strict: true
        # Required status checks
        contexts:
          - "Security Audit"
          - "Lint and Type Check"
          - "Run Tests"
          - "Build Application"
      
      # Enforce all configured restrictions for administrators
      enforce_admins: false
      
      # Prevent direct pushes to the branch
      restrictions:
        users: []
        teams: []
        apps: []
      
      # Allow force pushes and deletions
      allow_force_pushes: false
      allow_deletions: false
      
      # Require signed commits
      required_signatures: false
      
      # Require linear history
      required_linear_history: false
      
      # Allow bypass for specific users/teams
      bypass_pull_request_allowances:
        users: []
        teams: []
        apps: []

# Additional settings
settings:
  # Delete head branches after merge
  delete_branch_on_merge: true
  
  # Allow squash merging
  allow_squash_merge: true
  
  # Allow merge commits
  allow_merge_commit: true
  
  # Allow rebase merging
  allow_rebase_merge: true
  
  # Default branch
  default_branch: main