name: 機能リクエスト
description: 新機能の提案や改善要望を提出する
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        新機能のご提案ありがとうございます。以下の情報を記入してください。
        
  - type: textarea
    id: summary
    attributes:
      label: 機能の概要
      description: 提案する機能について簡潔に説明してください
      placeholder: どのような機能を追加したいですか？
    validations:
      required: true
      
  - type: textarea
    id: motivation
    attributes:
      label: 動機・背景
      description: なぜこの機能が必要なのか、どのような問題を解決するのか説明してください
      placeholder: |
        - 現在どのような課題がありますか？
        - この機能によってどのような価値が提供されますか？
        - 誰がこの機能から恩恵を受けますか？
    validations:
      required: true
      
  - type: textarea
    id: detailed_description
    attributes:
      label: 詳細な要件
      description: 機能の詳細な動作や要件を記載してください
      placeholder: |
        - UIの変更点
        - 必要な設定項目
        - データの扱い方
        - エッジケースの考慮
    validations:
      required: true
      
  - type: textarea
    id: user_story
    attributes:
      label: ユーザーストーリー
      description: ユーザー視点でのストーリーを記載してください（任意）
      placeholder: |
        〇〇として、
        △△したい、
        なぜなら□□だから
    validations:
      required: false
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したと判断できる条件を列挙してください
      placeholder: |
        - [ ] ユーザーが〇〇できる
        - [ ] △△の場合にエラーが表示される
        - [ ] パフォーマンスが□□以内
    validations:
      required: true
      
  - type: textarea
    id: mockups
    attributes:
      label: モックアップ・デザイン案
      description: UIの変更を伴う場合、モックアップやワイヤーフレームを添付してください
      placeholder: 画像をドラッグ&ドロップまたはペーストしてください
    validations:
      required: false
      
  - type: dropdown
    id: platforms
    attributes:
      label: 対象プラットフォーム
      description: どのプラットフォームに実装を希望しますか？
      multiple: true
      options:
        - iOS
        - Android
        - Web
        - すべて
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の重要度を選択してください
      options:
        - 低（Nice to have）
        - 中（Should have）
        - 高（Must have）
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した他の解決策があれば記載してください
      placeholder: 他にどのような方法を検討しましたか？
    validations:
      required: false
      
  - type: textarea
    id: technical_considerations
    attributes:
      label: 技術的な考慮事項
      description: 実装に関する技術的な懸念や提案があれば記載してください
      placeholder: |
        - 使用する技術やライブラリ
        - パフォーマンスへの影響
        - セキュリティの考慮事項
        - 既存機能への影響
    validations:
      required: false
      
  - type: dropdown
    id: breaking_change
    attributes:
      label: 破壊的変更
      description: この機能は既存の動作に影響を与えますか？
      options:
        - いいえ
        - はい - 後方互換性あり
        - はい - 後方互換性なし
    validations:
      required: true
      
  - type: textarea
    id: additional_context
    attributes:
      label: その他の情報
      description: その他、実装に役立つ情報があれば記入してください
      placeholder: 参考リンク、類似機能の例など
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      description: 提出前に以下を確認してください
      options:
        - label: 既存のIssueに同じ提案がないことを確認しました
          required: true
        - label: この機能がプロジェクトの方向性に合致していることを確認しました
          required: true